# Generated by Django 2.0 on 2018-03-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=200)),
                ('ruolo', models.CharField(max_length=200)),
                ('sede', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Dipendenti',
            },
        ),
    ]
